library(ggplot2) 
flow <- read.csv("~/Documents/code/github/lucachaves/lattesGephi/src/flow/lattes-flow-interval.csv")
hist(flow$interval)
hist(flow$interval, breaks = 20)
hist(flow$interval, breaks = 20, col = "gray", labels = TRUE)
hist(flow$interval[1:20000], breaks = 200, col = "gray")