library(ggplot2) 
flow <- read.csv("~/Documents/code/github/lucachaves/lattesGephi/src/flow-edges/distance/lattes-flow-distance-year.csv")
is.list(flow)
is.vector(flow$distances)
sumary(flow$distances)
sort(flow$distances)
plot(density(flow$distances))
hist(flow$distances)
hist(flow$distances, breaks = 20)
hist(flow$distances, breaks = 20, col = "gray", labels = TRUE)
hist(flow$distances[1:20000], breaks = 200, col = "gray")
hist(log(flow$distances+1), col = "gray")
plot(flow$distances, flow$years)
plot(flow$years, flow$distances, xlim=c(1940,2014))

# http://stackoverflow.com/questions/7714677/r-scatterplot-with-too-many-points
df <- data.frame(x = rnorm(5000),y=rnorm(5000))
ggplot(df,aes(x=x,y=y)) + geom_point(alpha = 0.3)
ggplot(df,aes(x=x,y=y)) + stat_binhex()